languageCode = "en-us"
title = "TutorialEdge.net"
baseURL = "https://tutorialedge.net"

# only return 9 items per page
paginate = 9

# Syntax highlighting stuff
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"

# index for algolia
[indexes] 
    category = "categories" 
    tag = "tags" 
    series = "series"
    course = "course"
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
[params.algolia]
    vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink", "description", "image"]
    params = ["categories", "tags"]
[outputs]
    home = ["HTML", "RSS", "Algolia"]
